export default {
  success: true,
  data: {
    memes: [
      {
        id: "aag",
        name: "Ancient Aliens Guy",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/aag.png",
        url: "https://api.memegen.link/images/aag/_/aliens.png",
      },
      {
        id: "ackbar",
        name: "It's A Trap!",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/ackbar.png",
        url: "https://api.memegen.link/images/ackbar/_/it's_a_trap!.png",
      },
      {
        id: "afraid",
        name: "Afraid to Ask Andy",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/afraid.png",
        url: "https://api.memegen.link/images/afraid/i_don't_know_what_this_meme_is_for/and_at_this_point_i'm_too_afraid_to_ask.png",
      },
      {
        id: "agnes",
        name: "Agnes Harkness Winking",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/agnes.png",
        url: "https://api.memegen.link/images/agnes/_/i_have_read_and_agree_to_the_terms_and_conditions.png",
      },
      {
        id: "aint-got-time",
        name: "Sweet Brown",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/aint-got-time.png",
        url: "https://api.memegen.link/images/aint-got-time/memes~q/ain't_nobody_got_time_fo'_that.png",
      },
      {
        id: "ams",
        name: "Awkward Moment Seal",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/ams.png",
        url: "https://api.memegen.link/images/ams/when_you're_watching_a_movie/and_your_parents_walk_in_at_the_sex_scene.png",
      },
      {
        id: "ants",
        name: "Do You Want Ants?",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/ants.png",
        url: "https://api.memegen.link/images/ants/do_you_want_ants~q/because_that's_how_you_get_ants.png",
      },
      {
        id: "apcr",
        name: "Almost Politically Correct Redneck",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/apcr.png",
        url: "https://api.memegen.link/images/apcr/I_supported_my_sister's_abortion/Still_would_have_been_cool_to_be_a_dad.png",
      },
      {
        id: "astronaut",
        name: "Always Has Been",
        lines: 4,
        overlays: 1,
        styles: ["default"],
        blank: "https://api.memegen.link/images/astronaut.png",
        url: "https://api.memegen.link/images/astronaut/Wait,_it's_round~q/Always_has_been/Flat_Earther/Science.png",

        source:
          "https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been",
        keywords: [],
        _self: "https://api.memegen.link/templates/astronaut",
      },
      {
        id: "atis",
        name: "And Then I Said",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/atis.png",
        url: "https://api.memegen.link/images/atis/and_then_i_said/the_exam_will_only_contain_what_we've_covered_in_lectures.png",
        example: {
          text: [
            "and then i said",
            "the exam will only contain what we've covered in lectures",
          ],
        },
        source: "https://knowyourmeme.com/memes/and-then-i-said",
        keywords: [],
        _self: "https://api.memegen.link/templates/atis",
      },
      {
        id: "away",
        name: "Life... Finds a Way",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/away.png",
        url: "https://api.memegen.link/images/away/life.../finds_a_way.png",
        example: {
          text: ["life...", "finds a way"],
        },
        source: "https://www.youtube.com/watch?v=dMjQ3hA9mEA",
        keywords: ["Jurassic Park"],
        _self: "https://api.memegen.link/templates/away",
      },
      {
        id: "awesome",
        name: "Socially Awesome Penguin",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/awesome.png",
        url: "https://api.memegen.link/images/awesome/say_a_word_wrong/create_hilarious_inside_joke.png",
        example: {
          text: ["say a word wrong", "create hilarious inside joke"],
        },
        source: "http://knowyourmeme.com/memes/socially-awesome-penguin",
        keywords: [],
        _self: "https://api.memegen.link/templates/awesome",
      },
      {
        id: "awesome-awkward",
        name: "Socially Awesome Awkward Penguin",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/awesome-awkward.png",
        url: "https://api.memegen.link/images/awesome-awkward/first_day_at_new_job/spill_coffee_on_bossman.png",
        example: {
          text: ["first day at new job", "spill coffee on bossman"],
        },
        source: "http://knowyourmeme.com/memes/socially-awkward-penguin",
        keywords: [],
        _self: "https://api.memegen.link/templates/awesome-awkward",
      },
      {
        id: "awkward",
        name: "Socially Awkward Penguin",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/awkward.png",
        url: "https://api.memegen.link/images/awkward/start_telling_joke/forget_punchline.png",
        example: {
          text: ["start telling joke", "forget punchline"],
        },
        source: "http://knowyourmeme.com/memes/socially-awkward-penguin",
        keywords: [],
        _self: "https://api.memegen.link/templates/awkward",
      },
      {
        id: "awkward-awesome",
        name: "Socially Awkward Awesome Penguin",
        lines: 2,
        overlays: 0,
        styles: [],
        blank: "https://api.memegen.link/images/awkward-awesome.png",
        url: "https://api.memegen.link/images/awkward-awesome/trip_guy_on_the_street/he_was_running_with_a_stolen_purse.png",
        example: {
          text: [
            "trip guy on the street",
            "he was running with a stolen purse",
          ],
        },
        source: "http://knowyourmeme.com/memes/socially-awkward-penguin",
        keywords: [],
        _self: "https://api.memegen.link/templates/awkward-awesome",
      },
    ],
  },
};
